apiVersion: v1
kind: Pod
metadata:
  labels:
    run: centos-2
  name: centos-2
  namespace: multus-test
  annotations:
    k8s.v1.cni.cncf.io/networks: macvlan-conf-2, macvlan-conf-2
spec:
  containers:
  - image: centos
    name: centos
    command: ["tail", "-f", "/dev/null"]
  imagePullSecrets:
    - name: dockerhub-cred
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  nodeSelector:
    kubernetes.io/hostname: iks-sarimits-worker-dc08bfec20
