apiVersion: v1
kind: Pod
metadata:
  labels:
    run: centos
  name: centos
  namespace: multus-test
  annotations:
    k8s.v1.cni.cncf.io/networks: macvlan-conf
spec:
  containers:
  - image: centos
    name: centos
    command: ["tail", "-f", "/dev/null"]
  imagePullSecrets:
    - name: dockerhub-cred
  dnsPolicy: ClusterFirst
  restartPolicy: Always
