apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: macvlan-conf-2
  namespace: multus-test
spec:
  config: '{
      "cniVersion": "0.3.0",
      "type": "macvlan",
      "master": "ens224",
      "mode": "bridge",
      "ipam": {
        "type": "host-local",
        "subnet": "1.1.1.0/24",
        "rangeStart": "1.1.1.11",
        "rangeEnd": "1.1.1.20",
        "routes": [
          { "dst": "0.0.0.0/0" }
        ],
        "gateway": "1.1.1.254"
      }
    }'
